FROM php:8-fpm

RUN apt-get update 
RUN apt-get install -y apt-file && apt-file update
RUN apt-get install -y htop grep
RUN apt-get install -y zlib1g zlib1g-dev


RUN apt-get install -y libmemcached-dev curl

# Install Memcached for php 8
RUN curl -L -o /tmp/memcached.tar.gz "https://pecl.php.net/get/memcached-3.1.5.tgz" \
    && mkdir -p /usr/src/php/ext/memcached \
    && tar -C /usr/src/php/ext/memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
    && docker-php-ext-configure memcached \
    && docker-php-ext-install memcached \
    && rm /tmp/memcached.tar.gz

# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql pcntl posix


RUN apt-get -y install python3
# Timezone
ENV TZ=Europe/Paris
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata 


RUN apt-get install -y vim