FROM php:8.1-apache
RUN apt-get update 
# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
RUN a2enmod rewrite

# Installer ffmpeg, youtube-dl en téléchargement avec curl/wget
