FROM  nginx:1.21.6-alpine

RUN apk add --update autoconf g++ libtool make
RUN apk upgrade 


# Install Postgre PDO
# RUN apk add libpq-dev
# RUN apk add docker-php-ext-install pgsql
# RUN apk add docker-php-ext-install pdo
# RUN apk add docker-php-ext-install pdo_pgsql


# install python (for youtube-dl)
RUN apk add python3

# configure timezone
ENV TZ=Europe/Paris
ENV DEBIAN_FRONTEND=noninteractive
RUN apk add tzdata